global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'ova-entertainment-api'
    static_configs:
      - targets: ['ova-entertainment-api:9100']