// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ova_entertainment_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	CreateEntertainmentV1(ctx context.Context, in *CreateEntertainmentV1Request, opts ...grpc.CallOption) (*EntertainmentV1Response, error)
	DescribeEntertainmentV1(ctx context.Context, in *DescribeEntertainmentV1Request, opts ...grpc.CallOption) (*EntertainmentV1Response, error)
	ListEntertainmentsV1(ctx context.Context, in *ListEntertainmentV1Request, opts ...grpc.CallOption) (*ListEntertainmentsV1Response, error)
	RemoveEntertainmentV1(ctx context.Context, in *RemoveEntertainmentV1Request, opts ...grpc.CallOption) (*RemoveV1Response, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) CreateEntertainmentV1(ctx context.Context, in *CreateEntertainmentV1Request, opts ...grpc.CallOption) (*EntertainmentV1Response, error) {
	out := new(EntertainmentV1Response)
	err := c.cc.Invoke(ctx, "/ova.entertainment.api.api/CreateEntertainmentV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) DescribeEntertainmentV1(ctx context.Context, in *DescribeEntertainmentV1Request, opts ...grpc.CallOption) (*EntertainmentV1Response, error) {
	out := new(EntertainmentV1Response)
	err := c.cc.Invoke(ctx, "/ova.entertainment.api.api/DescribeEntertainmentV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ListEntertainmentsV1(ctx context.Context, in *ListEntertainmentV1Request, opts ...grpc.CallOption) (*ListEntertainmentsV1Response, error) {
	out := new(ListEntertainmentsV1Response)
	err := c.cc.Invoke(ctx, "/ova.entertainment.api.api/ListEntertainmentsV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RemoveEntertainmentV1(ctx context.Context, in *RemoveEntertainmentV1Request, opts ...grpc.CallOption) (*RemoveV1Response, error) {
	out := new(RemoveV1Response)
	err := c.cc.Invoke(ctx, "/ova.entertainment.api.api/RemoveEntertainmentV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility
type ApiServer interface {
	CreateEntertainmentV1(context.Context, *CreateEntertainmentV1Request) (*EntertainmentV1Response, error)
	DescribeEntertainmentV1(context.Context, *DescribeEntertainmentV1Request) (*EntertainmentV1Response, error)
	ListEntertainmentsV1(context.Context, *ListEntertainmentV1Request) (*ListEntertainmentsV1Response, error)
	RemoveEntertainmentV1(context.Context, *RemoveEntertainmentV1Request) (*RemoveV1Response, error)
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (UnimplementedApiServer) CreateEntertainmentV1(context.Context, *CreateEntertainmentV1Request) (*EntertainmentV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntertainmentV1 not implemented")
}
func (UnimplementedApiServer) DescribeEntertainmentV1(context.Context, *DescribeEntertainmentV1Request) (*EntertainmentV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeEntertainmentV1 not implemented")
}
func (UnimplementedApiServer) ListEntertainmentsV1(context.Context, *ListEntertainmentV1Request) (*ListEntertainmentsV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEntertainmentsV1 not implemented")
}
func (UnimplementedApiServer) RemoveEntertainmentV1(context.Context, *RemoveEntertainmentV1Request) (*RemoveV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveEntertainmentV1 not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_CreateEntertainmentV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntertainmentV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).CreateEntertainmentV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova.entertainment.api.api/CreateEntertainmentV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).CreateEntertainmentV1(ctx, req.(*CreateEntertainmentV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_DescribeEntertainmentV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeEntertainmentV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).DescribeEntertainmentV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova.entertainment.api.api/DescribeEntertainmentV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).DescribeEntertainmentV1(ctx, req.(*DescribeEntertainmentV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ListEntertainmentsV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntertainmentV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ListEntertainmentsV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova.entertainment.api.api/ListEntertainmentsV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ListEntertainmentsV1(ctx, req.(*ListEntertainmentV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RemoveEntertainmentV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveEntertainmentV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RemoveEntertainmentV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova.entertainment.api.api/RemoveEntertainmentV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RemoveEntertainmentV1(ctx, req.(*RemoveEntertainmentV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ova.entertainment.api.api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntertainmentV1",
			Handler:    _Api_CreateEntertainmentV1_Handler,
		},
		{
			MethodName: "DescribeEntertainmentV1",
			Handler:    _Api_DescribeEntertainmentV1_Handler,
		},
		{
			MethodName: "ListEntertainmentsV1",
			Handler:    _Api_ListEntertainmentsV1_Handler,
		},
		{
			MethodName: "RemoveEntertainmentV1",
			Handler:    _Api_RemoveEntertainmentV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ova-entertainment-api/api.proto",
}
